[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.dfx-build]
description = "Build canisters"
dependencies = []
script = "./scripts/dfx-build.sh"
workspace = false

[tasks.run]
description = "Run app"
dependencies = []
command = "cargo"
args = ["run"]
workspace = false

[tasks.test]
description = "Run unit tests"
command = "cargo"
args = ["test", "--lib"]
dependencies = ["did"]
workspace = false

[tasks.integration-tests]
description = "Run integration tests"
script = "./scripts/integration-tests.sh"
dependencies = ["did", "dfx-build"]
workspace = false

[tasks.deploy-local]
description = "Deploy testnet with dfx"
script = "./scripts/deploy_local.sh"
dependencies = ["dfx-setup", "dfx-build", "did"]
workspace = false

[tasks.lint]
description = "Run lint"
command = "cargo"
args = ["clippy", "--", "-Dwarnings"]
workspace = false

[tasks.format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all"]

[tasks.check-format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.did]
description = "Generate did files"
dependencies = ["ledger-did", "swap-did", "dfx-generate"]
workspace = false

[tasks.ledger-did]
description = "Generate did files for ledger"
script = "cargo run --bin ledger-did  --features did > src/ledger/ledger.did"
workspace = false

[tasks.swap-did]
description = "Generate did files for swap"
script = "cargo run --bin swap-did  --features did > src/swap/swap.did"
workspace = false

[tasks.dfx-generate]
description = "Generate dfx did"
command = "dfx"
args = ["generate"]
workspace = false

[tasks.dfx-setup]
description = "setup dfx"
script = "./scripts/dfx-setup.sh"
workspace = false
